# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
np.__version__

'1.18.1'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1

a = np.random.random((2,3,5))
a

array([[[0.3155343 , 0.47350625, 0.54732779, 0.03752085, 0.18874941],
        [0.5628076 , 0.50794702, 0.1478631 , 0.9203795 , 0.64262479],
        [0.73261502, 0.5489053 , 0.411472  , 0.82928629, 0.42805315]],

       [[0.15869922, 0.74323196, 0.15337488, 0.99554074, 0.5715214 ],
        [0.76535079, 0.89162616, 0.16280319, 0.10110127, 0.70172983],
        [0.31560334, 0.38057648, 0.90603688, 0.52238588, 0.32316415]]])

In [4]:
# Method 2

a_2 = np.random.randint(0, 100, size=(2,3,5))
a_2

array([[[70, 58, 20, 67, 20],
        [61, 90, 85, 86, 86],
        [21,  6, 60, 89, 24]],

       [[98, 51, 47, 13, 95],
        [ 7, 11, 62, 35, 26],
        [52, 48, 94, 64,  7]]])

In [5]:
# Method 3

a_3 = np.random.normal(size=(2,3,5))
a_3

array([[[ 0.7932553 ,  0.27233751,  0.29348006,  1.11817623,
         -0.24345305],
        [ 0.04811277,  2.12819487, -1.81798859, -1.12093107,
         -0.91840556],
        [ 0.44115676,  1.72897127,  0.50546593, -0.37791672,
         -0.49608508]],

       [[-0.08613316,  1.35208038, -1.28123877,  0.36440535,
          0.80722817],
        [-0.86371701, -0.22565331,  1.19486223, -1.74456355,
          1.52837658],
        [ 1.54296916,  0.92547457, -1.34667351,  0.23412719,
         -0.28883152]]])

#### 4. Print *a*.


In [6]:
# your code here
print(a)
a.shape

[[[0.3155343  0.47350625 0.54732779 0.03752085 0.18874941]
  [0.5628076  0.50794702 0.1478631  0.9203795  0.64262479]
  [0.73261502 0.5489053  0.411472   0.82928629 0.42805315]]

 [[0.15869922 0.74323196 0.15337488 0.99554074 0.5715214 ]
  [0.76535079 0.89162616 0.16280319 0.10110127 0.70172983]
  [0.31560334 0.38057648 0.90603688 0.52238588 0.32316415]]]


(2, 3, 5)

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here
#Randint controla values
b = np.random.randint(1, 2, size=(5,2,3))
b

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

#### 6. Print *b*.


In [8]:
# your code here
print(b)
b.shape

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


(5, 2, 3)

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here
a.size

30

In [10]:
b.size

30

#### 8. Are you able to add *a* and *b*? Why or why not?


In [11]:
# your answer here

#a e b tem o mesmo tamanho mas não o mesmo formato, não podem ser somados
a+b

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [12]:
c = b.T
c

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [13]:
c.shape


(3, 2, 5)

In [14]:
a+c

ValueError: operands could not be broadcast together with shapes (2,3,5) (3,2,5) 

In [15]:
# your code here
# Ainda estavam com shapes diferentes, usei reshape para "forçar"o (2,3,5)

c = b.reshape(2,3,5)
c


array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [16]:
c.shape

(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [17]:
# your code/answer here

d = a+c
d

array([[[1.3155343 , 1.47350625, 1.54732779, 1.03752085, 1.18874941],
        [1.5628076 , 1.50794702, 1.1478631 , 1.9203795 , 1.64262479],
        [1.73261502, 1.5489053 , 1.411472  , 1.82928629, 1.42805315]],

       [[1.15869922, 1.74323196, 1.15337488, 1.99554074, 1.5715214 ],
        [1.76535079, 1.89162616, 1.16280319, 1.10110127, 1.70172983],
        [1.31560334, 1.38057648, 1.90603688, 1.52238588, 1.32316415]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [18]:
# your code/answer here
print(a)
a.size

[[[0.3155343  0.47350625 0.54732779 0.03752085 0.18874941]
  [0.5628076  0.50794702 0.1478631  0.9203795  0.64262479]
  [0.73261502 0.5489053  0.411472   0.82928629 0.42805315]]

 [[0.15869922 0.74323196 0.15337488 0.99554074 0.5715214 ]
  [0.76535079 0.89162616 0.16280319 0.10110127 0.70172983]
  [0.31560334 0.38057648 0.90603688 0.52238588 0.32316415]]]


30

In [19]:
print(d)
d.size

[[[1.3155343  1.47350625 1.54732779 1.03752085 1.18874941]
  [1.5628076  1.50794702 1.1478631  1.9203795  1.64262479]
  [1.73261502 1.5489053  1.411472   1.82928629 1.42805315]]

 [[1.15869922 1.74323196 1.15337488 1.99554074 1.5715214 ]
  [1.76535079 1.89162616 1.16280319 1.10110127 1.70172983]
  [1.31560334 1.38057648 1.90603688 1.52238588 1.32316415]]]


30

In [20]:
#DUVIDA

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [21]:
# your code here

e = a*c
e

array([[[0.3155343 , 0.47350625, 0.54732779, 0.03752085, 0.18874941],
        [0.5628076 , 0.50794702, 0.1478631 , 0.9203795 , 0.64262479],
        [0.73261502, 0.5489053 , 0.411472  , 0.82928629, 0.42805315]],

       [[0.15869922, 0.74323196, 0.15337488, 0.99554074, 0.5715214 ],
        [0.76535079, 0.89162616, 0.16280319, 0.10110127, 0.70172983],
        [0.31560334, 0.38057648, 0.90603688, 0.52238588, 0.32316415]]])

In [22]:
e.size

30

#### 13. Does *e* equal to *a*? Why or why not?


In [23]:
# your code/answer here

#DUVIDA, um é int e o outro é float?

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [24]:
# your code here
    
d_mean = np.mean(d)
d_mean

1.4995779520128754

In [25]:
d_max = np.max(d)
d_max

1.9955407417129654

In [26]:
d_min = np.min(d)
d_min

1.0375208522950614

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [28]:
# your code here


f = np.empty([2,3,5], dtype=object)
f

array([[[None, None, None, None, None],
        [None, None, None, None, None],
        [None, None, None, None, None]],

       [[None, None, None, None, None],
        [None, None, None, None, None],
        [None, None, None, None, None]]], dtype=object)

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [35]:
# Percorrer o f: popular o f com o valor de d , com as condicoes acima!
# array([[[0.07724812, 0.67893809, 0.46153521, 0.47335133, 0.39476616],
#         [0.76482841, 0.57207577, 0.34429473, 0.35028056, 0.94911205],
#         [0.24083809, 0.25972826, 0.64292927, 0.53846355, 0.72781957]],

#        [[0.48811861, 0.67345328, 0.30169981, 0.92558362, 0.75566578],
#         [0.37741449, 0.31336193, 0.67140443, 0.28208513, 0.62496195],
#         [0.27658545, 0.99957954, 0.61278603, 0.7176804 , 0.03091899]]])


#For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
#d_min --> 1.0008323714082055
#d_mean --> 1.5229421468028395

# for lista in f:
#     for item in lista:
#         for elemento in item:
#             if elemento > d_min and elemento < d_mean:
#                 elemento = 25
                
# print(f) # errado
 
for i in range(f.shape[0]):
    for j in range(f.shape[1]):
        for k in range(f.shape[2]):
            if d[i,j,k] > d_min and d[i,j,k] < d_mean:
                f[i,j,k]=25
            elif d[i,j,k] > d_mean and d[i,j,k] < d_max:
                f[i,j,k]=75
            elif d[i,j,k] == d_mean:
                f[i,j,k]=50
            elif d[i,j,k] == d_min:
                f[i,j,k]=0
            elif d[i,j,k] == d_max:
                f[i,j,k]=100
print(f)

    
    
    

[[[25 25 75 0 25]
  [75 75 25 75 75]
  [75 75 25 75 25]]

 [[25 75 25 100 75]
  [75 75 25 25 75]
  [25 25 75 75 25]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [44]:
p = np.empty([2,3,5], dtype=object)
p

array([[[None, None, None, None, None],
        [None, None, None, None, None],
        [None, None, None, None, None]],

       [[None, None, None, None, None],
        [None, None, None, None, None],
        [None, None, None, None, None]]], dtype=object)

In [46]:
# your code here



for i in range(p.shape[0]):
    for j in range(p.shape[1]):
        for k in range(p.shape[2]):
            if f[i,j,k] == 25:
                p[i,j,k]= 'A'
            elif f[i,j,k] == 75:
                p[i,j,k]= 'B'
            elif f[i,j,k] == 50:
                p[i,j,k]= 'C'
            elif f[i,j,k] == 0:
                p[i,j,k]= 'D'
            elif f[i,j,k] == 100:
                p[i,j,k]= 'E'
print(p)

[[['A' 'A' 'B' 'D' 'A']
  ['B' 'B' 'A' 'B' 'B']
  ['B' 'B' 'A' 'B' 'A']]

 [['A' 'B' 'A' 'E' 'B']
  ['B' 'B' 'A' 'A' 'B']
  ['A' 'A' 'B' 'B' 'A']]]


In [ ]:
# Another one bites the dusty!